<section class="page-header" style="background-image: url('./assets/images/Sanctuary-70.jpg');">
    <div>STUDYING HERE</div>
    <hr>
</section>

<section class="section studying-here-info-section">
    <img src="<?php echo get_template_directory_uri() ?>/assets/images/rectangle-placeholder.svg" alt="placeholder" width="448px;" height="283.38px;" />
    <div class="studying-here-info">The Israelite Academy invites applicants from people of any background who are sincerely interested in learning about Israelite history, culture, and practice. Our primary responsibility is to the members of our own community, but we welcome others who wish to study with us if there are sufficient resources to accommodate them and that those individuals conduct themselves in a respectful manner. We have recently opened our doors in this way to meet the growing demand we have received from our constituents and from the general public. While we are interested in meeting this legitimate thirst for knowledge, we realize that some individuals may be more interested in proselytizing, criticizing, and merely engaging in doctrinal debate for the purpose of advancing their own views. Individuals who may fit the latter description should seek other forums to air their beliefs. Perspective students should apply with the understanding that we are a private school with defined positions just as Orthodox Yeshivas, Catholic Seminaries, and Christian Bible Colleges. We encourage you to be a student; learn what we teach and then draw your own conclusions.</div>
    <div class="studying-here-info">
        Students may enroll in one of following programs:
        <br>
        <strong>1. The Independent Study Program;</strong>
        <br>
        <strong>2. General Education Program;</strong>
        <br>
        <strong>3. The Rabbinic Masters Program.</strong>
    </div>
    <div class="studying-here-info"><strong>The Independent Study Program</strong> is open to anyone who meets the minimal requirements explained above. Students in this program make take any course offered to the public at any of our sites or, if available, online through our distance-learning center. It is an entirely self-designed program where students may take as many or as few courses as they wish. Therefore, students in this program have the option of just taking courses that interest them with no further obligations. If there is a prerequisite—such as in a two-part course—students will be expected to take the courses in sequence. The rational for this program is to help students with their personal spiritual development. As such, it does not grant a degree or certificate; however, any credits acquired in this program may be applied to one of the degree programs, should a student decide to continue their education with us.</div>
    <div class="studying-here-info"><strong>The General Education Program</strong> requires a minimum of two years of study with us and completion of a core of course in Hebrew, Tephilah (Prayer), Torah, and History. At the end of the program successful men and women are award a certificate of completion that establishes their qualifications to teach in most Talmud Torah Schools operated by synagogues within our community.</div>
    <div class="studying-here-info"><strong>The Rabbinic Program</strong> exists solely to train rabbis who will serve our community. Each application will be reviewed by our admissions committee. Acceptance into the program is determined by the candidate’s level of academic preparation, the strength of his recommendations, and an interview conducted by designated faculty of the Israelite Academy. Those who complete all the graduation requirements will receive a masters degree in Rabbinic Doctrine. Ordination (conferring of Smecha) usually takes place at the same time of graduation; however, graduates may defer until such time that they are ready and the Dean of the Academy may withhold ordination from any student who failed to uphold the honor or principles of the Academy.</div>
</section>